# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 04:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+12394579799'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,13}$')])),
                ('language', models.CharField(choices=[('USA', 'ENGLISH-US'), ('UK', 'ENGLISH-UK'), ('Japan', 'JAPANESE'), ('China', 'MANDARIN'), ('France', 'FRENCH'), ('Germany', 'GERMAN'), ('Portugal', 'PORTUGUESE'), ('Spain', 'SPANISH')], max_length=6)),
                ('currency', models.CharField(choices=[('Europe', 'EUR'), ('Britain', 'GBP'), ('Japan', 'JPY'), ('USA', 'USD')], max_length=6)),
            ],
        ),
    ]
