# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 07:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+12394579799'. 9 to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
