# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 14:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_remove_service_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, dim=((0.4, 0.4), (0.4, 0.6), (0.6, 0.6), (0.6, 0.4), (0.4, 0.4)), null=True, srid=4326, verbose_name=((0, 0), (0, 1), (1, 1), (1, 0), (0, 0))),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
