# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 14:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_auto_20170711_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(dim=((0.4, 0.4), (0.4, 0.6), (0.6, 0.6), (0.6, 0.4), (0.4, 0.4)), srid=4326, verbose_name=((0, 0), (0, 1), (1, 1), (1, 0), (0, 0))),
        ),
    ]
