# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 14:58
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_auto_20170711_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
