# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_auto_20170711_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
