# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0012_auto_20170711_1533'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set([('provider', 'name')]),
        ),
    ]
